Repository AY2021S1-CS2113T-F11-4/tp, pull requests merged in 2020-10, with the labels that each got.

#12 classes instantiated
  src/main/java/seedu/duke/CommandExtract.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Member.java
  src/main/java/seedu/duke/Project.java
  src/main/java/seedu/duke/ProjectBacklog.java
  src/main/java/seedu/duke/Task.java
  src/main/java/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Enhancement, type.Story

#19 Parser v0.1
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/CommandSummary.java
  src/main/java/seedu/duke/command/MemberCommand.java
  src/main/java/seedu/duke/command/ProjectCommand.java
  src/main/java/seedu/duke/command/SprintCommand.java
  src/main/java/seedu/duke/command/TaskCommand.java
  src/main/java/seedu/duke/exception/DukeException.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: priority.High

#17 Sample Task function and parser
  src/main/java/scrumptious/Priority.java
  src/main/java/scrumptious/Task.java
Labels: priority.High, type.Enhancement

#28 Integration of project, backlog with parser
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Member.java
  src/main/java/seedu/duke/command/CommandSummary.java
  src/main/java/seedu/duke/command/MemberCommand.java
  src/main/java/seedu/duke/command/ProjectCommand.java
  src/main/java/seedu/duke/command/TaskCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/project/ProjectBacklog.java
  src/main/java/seedu/duke/project/ProjectMember.java
  src/main/java/seedu/duke/task/Priority.java
  src/main/java/seedu/duke/task/Task.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Review

#32 Task functions added
  src/main/java/seedu/duke/command/TaskCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, type.Story

#31 Add Storage Manager
  .gitignore
  build.gradle
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/test/java/seedu/duke/storage/StorageManagerTest.java
Labels: priority.High, severity.Medium

#34 Improved Gunit's task implementation
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/CommandSummary.java
  src/main/java/seedu/duke/command/TaskCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/task/Priority.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Enhancement, type.Story

#35 remove task - minor change
  src/main/java/seedu/duke/command/TaskCommand.java
  src/main/java/seedu/duke/project/ProjectBacklog.java
Labels: type.Task

#39 Integration
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/SprintCommand.java
  src/main/java/seedu/duke/command/member/MemberCommand.java
  src/main/java/seedu/duke/command/project/ProjectCommand.java
  src/main/java/seedu/duke/command/task/TaskCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, severity.High

#64 UI added for basic testing
  src/main/java/seedu/duke/command/member/MemberCommand.java
  src/main/java/seedu/duke/command/project/ProjectCommand.java
  src/main/java/seedu/duke/command/sprint/CreateSprintCommand.java
  src/main/java/seedu/duke/command/sprint/DeleteSprintTaskCommand.java
  src/main/java/seedu/duke/command/task/TaskCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/project/ProjectMember.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.Medium

#66 Refactored, added UI
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/member/MemberCommand.java
  src/main/java/seedu/duke/command/sprint/AddSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/AllocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/CreateSprintCommand.java
  src/main/java/seedu/duke/command/sprint/DeleteSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/SprintCommand.java
  src/main/java/seedu/duke/command/sprint/ViewSprintCommand.java
  src/main/java/seedu/duke/command/task/TaskCommand.java
  src/main/java/seedu/duke/model/Project.java
  src/main/java/seedu/duke/model/ProjectBacklog.java
  src/main/java/seedu/duke/model/ProjectMembers.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/project/ProjectBacklog.java
  src/main/java/seedu/duke/project/ProjectMembers.java
  src/main/java/seedu/duke/sprint/Member.java
  src/main/java/seedu/duke/sprint/Sprint.java
  src/main/java/seedu/duke/sprint/SprintList.java
  src/main/java/seedu/duke/sprint/Task.java
  src/main/java/seedu/duke/ui/old/Ui.java
Labels: priority.Medium, severity.Medium

#65 Added JUnit testing for Parser class
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: priority.High, type.Test

#67 Update Model Classes to be Jsonable
  .gitignore
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/project/ProjectBacklog.java
  src/main/java/seedu/duke/project/ProjectMembers.java
  src/main/java/seedu/duke/sprint/Member.java
  src/main/java/seedu/duke/sprint/Sprint.java
  src/main/java/seedu/duke/sprint/SprintList.java
  src/main/java/seedu/duke/sprint/Task.java
  src/main/java/seedu/duke/task/Priority.java
  src/main/java/seedu/duke/task/Task.java
  src/test/java/seedu/duke/storage/StorageManagerTest.java
Labels: priority.High, severity.High, type.Review, type.Task

#60 Integate Sprint commands with standardised UI and parser
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandSummary.java
  src/main/java/seedu/duke/command/project/ProjectCommand.java
  src/main/java/seedu/duke/command/sprint/AddSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/AllocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/CreateSprintCommand.java
  src/main/java/seedu/duke/command/sprint/DeleteSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/SprintCommand.java
  src/main/java/seedu/duke/command/sprint/ViewSprintCommand.java
  src/main/java/seedu/duke/command/task/TaskCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/project/ProjectBacklog.java
  src/main/java/seedu/duke/project/ProjectMembers.java
  src/main/java/seedu/duke/sprint/Member.java
  src/main/java/seedu/duke/sprint/Sprint.java
  src/main/java/seedu/duke/sprint/SprintList.java
  src/main/java/seedu/duke/task/Task.java
  src/main/java/seedu/duke/ui/Messages.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, severity.High, type.Task

#70 User guide
  docs/UserGuide.md
  src/main/java/seedu/duke/command/CommandSummary.java
  src/main/java/seedu/duke/command/project/ProjectCommand.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: priority.High, severity.Medium, type.Task

#73 User guide
  docs/UserGuide.md
  docs/_config.yml
Labels: type.Documentation

#71 Update on toString method for various classes, fixed bug on delete task command and added JUnit script for some Sprint commands
  src/main/java/seedu/duke/command/project/ProjectCommand.java
  src/main/java/seedu/duke/command/sprint/AddSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/AllocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/CreateSprintCommand.java
  src/main/java/seedu/duke/command/sprint/DeleteSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/ViewSprintCommand.java
  src/main/java/seedu/duke/command/task/TaskCommand.java
  src/main/java/seedu/duke/parser/DateTimeParser.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/project/ProjectBacklog.java
  src/main/java/seedu/duke/sprint/Sprint.java
  src/main/java/seedu/duke/sprint/SprintList.java
  src/main/java/seedu/duke/task/Task.java
  src/test/java/seedu/duke/command/sprint/AddSprintTaskCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, severity.High, type.Bug, type.Enhancement, type.Review

#81 Complete Integration of Storage Manager
  .gitignore
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/sprint/SprintCommand.java
  src/main/java/seedu/duke/command/task/TaskCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/project/ProjectBacklog.java
  src/main/java/seedu/duke/project/ProjectMembers.java
  src/main/java/seedu/duke/sprint/Member.java
  src/main/java/seedu/duke/sprint/Sprint.java
  src/main/java/seedu/duke/sprint/SprintList.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/main/java/seedu/duke/task/Priority.java
  src/main/java/seedu/duke/task/Task.java
  src/test/java/seedu/duke/storage/StorageManagerTest.java
  test-data/LOAD_EXPECTED_1.json
  test-data/SAVE_EXPECTED_1.json
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: priority.High, severity.High, type.Enhancement, type.Task

#82 J-Unit
  src/test/java/seedu/duke/project/ProjectMemberTest.java
  src/test/java/seedu/duke/project/ProjectTest.java
Labels: type.Test

#94 Added exception handling for most commands
  src/main/java/seedu/duke/command/CommandSummary.java
  src/main/java/seedu/duke/command/member/MemberCommand.java
  src/main/java/seedu/duke/command/project/ProjectCommand.java
  src/main/java/seedu/duke/command/task/TaskCommand.java
  src/main/java/seedu/duke/parser/ExceptionsParser.java
  src/main/java/seedu/duke/parser/MemberParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/ProjectParser.java
  src/main/java/seedu/duke/parser/SprintParser.java
  src/main/java/seedu/duke/parser/TaskParser.java
Labels: priority.High, severity.High

#91 Update all sprint commands to use hashtable
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandSummary.java
  src/main/java/seedu/duke/command/sprint/AddSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/AllocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/CreateSprintCommand.java
  src/main/java/seedu/duke/command/sprint/RemoveSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/SprintCommand.java
  src/main/java/seedu/duke/command/task/TaskCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/SprintParser.java
  src/test/java/seedu/duke/command/sprint/AddSprintTaskCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, severity.Medium, type.Enhancement

#95 Added JUnit only
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/ProjectParser.java
  src/test/java/seedu/duke/command/TaskCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#99 User guide v2.0
  docs/UserGuide.md
Labels: priority.High, type.Documentation, type.Task

#107 refactored into hash tables
  src/main/java/seedu/duke/command/CommandSummary.java
  src/main/java/seedu/duke/command/project/CreateProjectCommand.java
  src/main/java/seedu/duke/command/project/ProjectCommand.java
  src/main/java/seedu/duke/command/project/SelectProjectCommand.java
  src/main/java/seedu/duke/command/project/ViewProjectCommand.java
  src/main/java/seedu/duke/parser/ProjectParser.java
  src/main/java/seedu/duke/project/Project.java
  src/main/java/seedu/duke/ui/Messages.java
  src/test/java/seedu/duke/project/ProjectMemberTest.java
  src/test/java/seedu/duke/project/ProjectTest.java
  src/test/java/seedu/duke/storage/StorageManagerTest.java
Labels: priority.High, severity.Medium

#108 updated with ProjectList, select command
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/member/MemberCommand.java
  src/main/java/seedu/duke/command/project/CreateProjectCommand.java
  src/main/java/seedu/duke/command/project/ProjectCommand.java
  src/main/java/seedu/duke/command/project/SelectProjectCommand.java
  src/main/java/seedu/duke/command/project/ViewProjectCommand.java
  src/main/java/seedu/duke/command/sprint/AddSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/AllocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/CreateSprintCommand.java
  src/main/java/seedu/duke/command/sprint/RemoveSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/ViewSprintCommand.java
  src/main/java/seedu/duke/command/task/TaskCommand.java
  src/main/java/seedu/duke/model/project/ProjectList.java
  src/main/java/seedu/duke/parser/ExceptionsParser.java
  src/main/java/seedu/duke/parser/MemberParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/ProjectParser.java
  src/main/java/seedu/duke/parser/SprintParser.java
  src/main/java/seedu/duke/parser/TaskParser.java
  src/test/java/seedu/duke/command/project/CreateProjectCommandTest.java
  src/test/java/seedu/duke/command/project/SelectProjectCommandTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
  src/test/java/seedu/duke/project/ProjectBacklogTest.java
Labels: priority.High, severity.High

#109 Update Developer Guide
  docs/DeveloperGuide.md
  docs/image/developerguide/savingdata1.png
  docs/image/developerguide/savingdata2.png
  docs/image/developerguide/storagecomponent.png
Labels: priority.Medium, type.Documentation, type.Task

#111 exception handling
  src/main/java/seedu/duke/command/member/AddMemberCommand.java
  src/main/java/seedu/duke/command/member/DeleteMemberCommand.java
  src/main/java/seedu/duke/command/member/MemberCommand.java
  src/main/java/seedu/duke/command/project/CreateProjectCommand.java
  src/main/java/seedu/duke/command/project/SelectProjectCommand.java
  src/main/java/seedu/duke/command/project/ViewProjectCommand.java
  src/main/java/seedu/duke/command/sprint/AddSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/AllocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/RemoveSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/ViewSprintCommand.java
  src/main/java/seedu/duke/model/project/ProjectList.java
  src/main/java/seedu/duke/parser/MemberParser.java
  src/main/java/seedu/duke/parser/ProjectParser.java
Labels: severity.High, type.Bug

#110 Implement Gunit-style refactoring
  src/main/java/seedu/duke/command/task/AddTaskCommand.java
  src/main/java/seedu/duke/command/task/ChangeTaskPriorityCommand.java
  src/main/java/seedu/duke/command/task/DeleteTaskCommand.java
  src/main/java/seedu/duke/command/task/DoneTaskCommand.java
  src/main/java/seedu/duke/command/task/TaskCommand.java
  src/main/java/seedu/duke/command/task/ViewTaskCommand.java
  src/main/java/seedu/duke/model/task/Task.java
  src/main/java/seedu/duke/model/task/TaskManager.java
  src/main/java/seedu/duke/parser/MemberParser.java
  src/main/java/seedu/duke/parser/ProjectParser.java
  src/main/java/seedu/duke/parser/SprintParser.java
  src/main/java/seedu/duke/parser/TaskParser.java
  src/test/java/seedu/duke/command/TaskCommandTest.java
Labels: priority.High, type.Task

#116 Added a help menu for SCRUMptious
  src/main/java/seedu/duke/command/CommandSummary.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/command/help/HelpCommand.java
  src/main/java/seedu/duke/command/help/MemberHelpCommand.java
  src/main/java/seedu/duke/command/help/ProjectHelpCommand.java
  src/main/java/seedu/duke/command/help/SprintHelpCommand.java
  src/main/java/seedu/duke/command/help/TaskHelpCommand.java
  src/main/java/seedu/duke/command/project/SelectProjectCommand.java
  src/main/java/seedu/duke/parser/HelpParser.java
  src/main/java/seedu/duke/parser/MemberParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/ProjectParser.java
Labels: priority.Medium, type.Enhancement, type.Task

#117 Storage Manager v1.1
  docs/DeveloperGuide.md
  docs/image/developerguide/storagecomponent.png
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/member/AddMemberCommand.java
  src/main/java/seedu/duke/command/member/DeleteMemberCommand.java
  src/main/java/seedu/duke/command/project/ProjectCommand.java
  src/main/java/seedu/duke/command/sprint/SprintCommand.java
  src/main/java/seedu/duke/command/task/AddTaskCommand.java
  src/main/java/seedu/duke/command/task/ChangeTaskPriorityCommand.java
  src/main/java/seedu/duke/model/member/Member.java
  src/main/java/seedu/duke/model/member/ProjectMembers.java
  src/main/java/seedu/duke/model/project/Project.java
  src/main/java/seedu/duke/model/project/ProjectManager.java
  src/main/java/seedu/duke/model/sprint/Sprint.java
  src/main/java/seedu/duke/model/sprint/SprintManager.java
  src/main/java/seedu/duke/model/task/Task.java
  src/main/java/seedu/duke/model/task/TaskManager.java
  src/main/java/seedu/duke/parser/SprintParser.java
  src/main/java/seedu/duke/storage/JsonableArray.java
  src/main/java/seedu/duke/storage/JsonableObject.java
  src/main/java/seedu/duke/storage/StorageManager.java
Labels: priority.High, type.Review, type.Task

#119 User guide
  docs/UserGuide.md
  src/main/java/seedu/duke/command/CommandSummary.java
  src/main/java/seedu/duke/command/member/AddMemberCommand.java
  src/main/java/seedu/duke/command/member/DeleteMemberCommand.java
  src/main/java/seedu/duke/command/project/ListProjectCommand.java
  src/main/java/seedu/duke/command/sprint/SprintCommand.java
  src/main/java/seedu/duke/model/member/ProjectMembers.java
  src/main/java/seedu/duke/model/project/ProjectManager.java
  src/main/java/seedu/duke/parser/ProjectParser.java
  src/main/java/seedu/duke/parser/SprintParser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/project/CreateProjectCommandTest.java
  src/test/java/seedu/duke/command/project/ViewProjectCommandTest.java
  src/test/java/seedu/duke/model/project/ProjectTest.java
Labels: type.Test

#120 editted
  docs/UserGuide.md
Labels: type.Documentation

#121 ug
  docs/UserGuide.md
Labels: type.Documentation

#118 Storage Manager v1.2
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandSummary.java
  src/main/java/seedu/duke/command/EmptyCommand.java
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/command/help/HelpCommand.java
  src/main/java/seedu/duke/command/help/MemberHelpCommand.java
  src/main/java/seedu/duke/command/help/ProjectHelpCommand.java
  src/main/java/seedu/duke/command/help/SprintHelpCommand.java
  src/main/java/seedu/duke/command/help/StorageHelpCommand.java
  src/main/java/seedu/duke/command/help/TaskHelpCommand.java
  src/main/java/seedu/duke/command/member/AddMemberCommand.java
  src/main/java/seedu/duke/command/member/DeleteMemberCommand.java
  src/main/java/seedu/duke/command/member/MemberCommand.java
  src/main/java/seedu/duke/command/project/CreateProjectCommand.java
  src/main/java/seedu/duke/command/project/ListProjectCommand.java
  src/main/java/seedu/duke/command/project/ProjectCommand.java
  src/main/java/seedu/duke/command/project/SelectProjectCommand.java
  src/main/java/seedu/duke/command/project/ViewProjectCommand.java
  src/main/java/seedu/duke/command/sprint/AddSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/AllocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/CreateSprintCommand.java
  src/main/java/seedu/duke/command/sprint/DeallocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/EditSprintCommand.java
  src/main/java/seedu/duke/command/sprint/RemoveSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/SprintCommand.java
  src/main/java/seedu/duke/command/sprint/ViewSprintCommand.java
  src/main/java/seedu/duke/command/storage/ClearStorageCommand.java
  src/main/java/seedu/duke/command/storage/StorageCommand.java
  src/main/java/seedu/duke/command/task/AddTaskCommand.java
  src/main/java/seedu/duke/command/task/ChangeTaskPriorityCommand.java
  src/main/java/seedu/duke/command/task/DeleteTaskCommand.java
  src/main/java/seedu/duke/command/task/DoneTaskCommand.java
  src/main/java/seedu/duke/command/task/TaskCommand.java
  src/main/java/seedu/duke/command/task/ViewTaskCommand.java
  src/main/java/seedu/duke/model/project/Project.java
  src/main/java/seedu/duke/model/project/ProjectManager.java
  src/main/java/seedu/duke/parser/HelpParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/StorageParser.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/storage/ClearStorageCommandTest.java
  src/test/java/seedu/duke/storage/StorageManagerTest.java
  test-data/LOAD_1.json
  test-data/LOAD_2.json
  test-data/LOAD_EXPECTED_1.json
  test-data/SAVE_1.json
  test-data/SAVE_EXPECTED_1.json
Labels: priority.High, type.Documentation, type.Enhancement, type.Task, type.Test

#124 User guide
  docs/DeveloperGuide.md
  docs/image/developerguide/architecturediagram.png
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/parser/HelpParser.java
  src/main/java/seedu/duke/parser/ParserManager.java
  src/main/java/seedu/duke/parser/ProjectParser.java
  src/main/java/seedu/duke/parser/TaskParser.java
Labels: type.Documentation

#123 Update SprintParser and Commands v2
  src/main/java/seedu/duke/command/sprint/AddSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/AllocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/CreateSprintCommand.java
  src/main/java/seedu/duke/command/sprint/DeallocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/EditSprintCommand.java
  src/main/java/seedu/duke/command/sprint/RemoveSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/SprintCommand.java
  src/main/java/seedu/duke/command/sprint/ViewSprintCommand.java
  src/main/java/seedu/duke/model/project/Project.java
  src/main/java/seedu/duke/model/sprint/Sprint.java
  src/main/java/seedu/duke/model/sprint/SprintManager.java
  src/main/java/seedu/duke/model/task/Task.java
  src/main/java/seedu/duke/model/task/TaskManager.java
  src/main/java/seedu/duke/parser/SprintParser.java
Labels: priority.High, type.Bug, type.Enhancement

#125 Update DG
  docs/DeveloperGuide.md
  docs/image/developerguide/parserandcommand.png
Labels: type.Documentation

#128 Update Developer Guide
  docs/DeveloperGuide.md
  docs/image/developerguide/storage_load.png
  docs/image/developerguide/storage_save.png
  docs/image/developerguide/storagecomponent.png
Labels: priority.High, type.Documentation

#129 Update DeveloperGuide (Model Component & CreateSprint)
  docs/DeveloperGuide.md
  docs/image/developerguide/createSprint.png
  docs/image/developerguide/modelcomponent.png
Labels: type.Documentation

#130 Update Developer Guide - Model Component
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/image/developerguide/modelcomponent.png
  logs/logfile
  src/main/resources/META-INF/MANIFEST.MF
Labels: type.Documentation

#133 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#136 Added help menu information to user guide
  docs/UserGuide.md
  src/main/java/seedu/duke/command/help/SprintHelpCommand.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: type.Documentation

#135 Bug fix
  src/main/java/seedu/duke/command/project/CreateProjectCommand.java
  src/main/java/seedu/duke/command/sprint/AddSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/AllocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/CreateSprintCommand.java
  src/main/java/seedu/duke/command/sprint/DeallocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/EditSprintCommand.java
  src/main/java/seedu/duke/command/sprint/RemoveSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/SprintCommand.java
  src/main/java/seedu/duke/command/sprint/ViewSprintCommand.java
  src/main/java/seedu/duke/command/task/AddTaskCommand.java
  src/main/java/seedu/duke/model/project/ProjectManager.java
  src/main/java/seedu/duke/model/sprint/Sprint.java
  src/main/java/seedu/duke/parser/HelpParser.java
  src/main/java/seedu/duke/parser/ParserManager.java
  src/main/java/seedu/duke/parser/ProjectParser.java
  src/main/java/seedu/duke/parser/TaskParser.java
Labels: priority.High, severity.Medium, type.Bug

#138 Doc v2.0
  docs/UserGuide.md
Labels: priority.High, type.Documentation, type.Task

#139 Update User Guide
  docs/UserGuide.md
Labels: type.Documentation, type.Task
