Repository AY2021S1-CS2113T-F11-4/tp, pull requests merged in 2020-11, with the labels that each got.

#182 Update help menu and developer guide
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/command/help/ProjectHelpCommand.java
Labels: type.Documentation

#183 Created a PPP draft
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/MingJun.md
Labels: type.Documentation

#187 Change storage load behaviour
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/storage/StorageManager.java
Labels: priority.High, severity.Low, type.Task

#189 Update JUnit
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/storage/ClearStorageCommandTest.java
  src/test/java/seedu/duke/storage/StorageManagerTest.java
Labels: priority.High, type.Task, type.Test

#186 Fix Developer Guide
  docs/DeveloperGuide.md
  docs/image/developerguide/savingdata1.png
  docs/image/developerguide/savingdata2.png
  docs/image/developerguide/storage_load.png
  docs/image/developerguide/storage_save.png
  docs/image/developerguide/storage_save_directory.png
  docs/image/userguide/directory.jpeg
Labels: priority.High, type.Documentation

#184 Task related updates
  src/main/java/seedu/duke/command/help/TaskHelpCommand.java
  src/main/java/seedu/duke/command/sprint/AddSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/AllocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/DeallocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/RemoveSprintTaskCommand.java
  src/main/java/seedu/duke/command/task/AddTaskCommand.java
  src/main/java/seedu/duke/command/task/ChangeTaskPriorityCommand.java
  src/main/java/seedu/duke/command/task/DeleteTaskCommand.java
  src/main/java/seedu/duke/command/task/DoneTaskCommand.java
  src/main/java/seedu/duke/command/task/PriorityViewCommand.java
  src/main/java/seedu/duke/command/task/ViewTaskCommand.java
  src/main/java/seedu/duke/model/project/Project.java
  src/main/java/seedu/duke/model/sprint/Sprint.java
  src/main/java/seedu/duke/model/task/Task.java
  src/main/java/seedu/duke/model/task/TaskManager.java
  src/test/java/seedu/duke/command/TaskCommandTest.java
  src/test/java/seedu/duke/command/task/AddTaskCommandTest.java
  src/test/java/seedu/duke/command/task/ChangeTaskPriorityCommandTest.java
  src/test/java/seedu/duke/command/task/DeleteTaskCommandTest.java
  src/test/java/seedu/duke/command/task/DoneTaskCommandTest.java
  src/test/java/seedu/duke/model/task/TaskManagerTest.java
  src/test/java/seedu/duke/model/task/TaskTest.java
Labels: priority.High, severity.Medium, type.Test

#198 Update ppp file name
  docs/AboutUs.md
  docs/team/homingjun.md
Labels: type.Documentation

#196 Fix storage load
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/storage/StorageManager.java
Labels: priority.High, severity.High, type.Bug

#200 Added logging for parser and help commands
  logs/scrum.log
  src/main/java/seedu/duke/command/InvalidCommand.java
  src/main/java/seedu/duke/command/help/HelpCommand.java
  src/main/java/seedu/duke/command/help/MainHelpCommand.java
  src/main/java/seedu/duke/command/help/MemberHelpCommand.java
  src/main/java/seedu/duke/command/help/ProjectHelpCommand.java
  src/main/java/seedu/duke/command/help/SprintHelpCommand.java
  src/main/java/seedu/duke/command/help/StorageHelpCommand.java
  src/main/java/seedu/duke/command/help/TaskHelpCommand.java
  src/main/java/seedu/duke/parser/ParserManager.java
Labels: priority.High, type.Task

#197 Added JUnit tests for parser classes
  .gitignore
  docs/team/homingjun.md
  src/test/java/seedu/duke/parser/HelpParserTest.java
  src/test/java/seedu/duke/parser/MemberParserTest.java
  src/test/java/seedu/duke/parser/ParserManagerTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
  src/test/java/seedu/duke/parser/ProjectParserTest.java
  src/test/java/seedu/duke/parser/StorageParserTest.java
  src/test/java/seedu/duke/parser/TaskParserTest.java
Labels: priority.High, type.Task, type.Test

#201 Many changes, for Task V2.1
  .gitignore
  logs/scrum.log
  src/main/java/seedu/duke/command/task/AddTaskCommand.java
  src/main/java/seedu/duke/command/task/ChangeTaskPriorityCommand.java
  src/main/java/seedu/duke/command/task/DeleteTaskCommand.java
  src/main/java/seedu/duke/command/task/DoneTaskCommand.java
  src/main/java/seedu/duke/command/task/PriorityViewCommand.java
  src/main/java/seedu/duke/command/task/TaskCommand.java
  src/main/java/seedu/duke/command/task/ViewTaskCommand.java
  src/main/java/seedu/duke/model/task/TaskManager.java
  src/test/java/seedu/duke/command/task/AddTaskCommandTest.java
  src/test/java/seedu/duke/command/task/ChangeTaskPriorityCommandTest.java
  src/test/java/seedu/duke/command/task/CommandTest.java
  src/test/java/seedu/duke/command/task/DeleteTaskCommandTest.java
  src/test/java/seedu/duke/command/task/DoneTaskCommandTest.java
Labels: priority.High, severity.Medium, type.Bug, type.Documentation, type.Task, type.Test

#208 Update Text Ui Testing
  .gitignore
  logs/logfile
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/sprint/CreateSprintCommand.java
  src/main/java/seedu/duke/command/sprint/DeallocateSprintTaskCommand.java
  src/main/java/seedu/duke/command/sprint/SprintCommand.java
  src/main/java/seedu/duke/model/project/Project.java
  src/main/java/seedu/duke/model/sprint/Sprint.java
  src/main/java/seedu/duke/model/sprint/SprintManager.java
  src/main/java/seedu/duke/parser/SprintParser.java
  src/main/java/seedu/duke/test/TextUiTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/expected2
  text-ui-test/input.txt
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
  text-ui-test/test2
Labels: priority.High, type.Enhancement, type.Task

#207 Duplicate project adding prevented
  src/main/java/seedu/duke/command/member/AddMemberCommand.java
  src/main/java/seedu/duke/command/member/DeleteMemberCommand.java
  src/main/java/seedu/duke/command/member/MemberCommand.java
  src/main/java/seedu/duke/command/project/CreateProjectCommand.java
  src/main/java/seedu/duke/command/project/ListProjectCommand.java
  src/main/java/seedu/duke/command/project/ProjectCommand.java
  src/main/java/seedu/duke/command/project/SelectProjectCommand.java
  src/main/java/seedu/duke/command/project/ViewProjectCommand.java
  src/main/java/seedu/duke/model/member/Member.java
  src/main/java/seedu/duke/model/member/ProjectMembers.java
  src/main/java/seedu/duke/parser/ProjectParser.java
Labels: priority.High, type.Bug, type.Task

#209 Storage manager v1.4
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/storage/ClearStorageCommand.java
  src/main/java/seedu/duke/storage/StorageManager.java
Labels: priority.High, type.Enhancement, type.Task

#214 Fix anchors in UG table of contents
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#215 Add and Remove Assertions
  src/main/java/seedu/duke/command/storage/ClearStorageCommand.java
  src/main/java/seedu/duke/command/task/AddTaskCommand.java
  src/main/java/seedu/duke/command/task/ChangeTaskPriorityCommand.java
  src/main/java/seedu/duke/command/task/DeleteTaskCommand.java
  src/main/java/seedu/duke/command/task/DoneTaskCommand.java
  src/main/java/seedu/duke/command/task/PriorityViewCommand.java
  src/main/java/seedu/duke/command/task/ViewTaskCommand.java
  src/main/java/seedu/duke/parser/MemberParser.java
  src/main/java/seedu/duke/parser/TaskParser.java
  src/main/java/seedu/duke/storage/StorageManager.java
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: priority.High, severity.High, type.Bug, type.Task

#213 Added javadoc comments
  src/main/java/seedu/duke/command/help/HelpCommand.java
  src/main/java/seedu/duke/exception/DukeException.java
  src/main/java/seedu/duke/parser/ExceptionsParser.java
  src/main/java/seedu/duke/parser/ParserManager.java
  src/main/java/seedu/duke/parser/TaskParser.java
Labels: priority.High, type.Documentation

#211 Update class diagrams for logic and sequence diagram for project implementation
  docs/DeveloperGuide.md
  docs/image/developerguide/commandClassDiagram.png
  docs/image/developerguide/createProjectSequenceDiagram.png
  docs/image/developerguide/parserManagerClassDiagram.png
  docs/image/developerguide/parserandcommand.png
Labels: priority.High, type.Documentation

#217 Add PPP
  docs/team/keke101.md
  src/main/java/seedu/duke/parser/ParserManager.java
Labels: priority.High, type.Documentation

#219 Update PPP
  docs/team/homingjun.md
Labels: priority.High, type.Documentation

#220 Add sequence diagram for create project
  docs/DeveloperGuide.md
  docs/image/developerguide/createProjectSequenceDiagram.png
Labels: priority.High, type.Documentation

#221 Update error printing for catchDate
  docs/team/chocomango.md
  src/main/java/seedu/duke/parser/DateTimeParser.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, severity.Medium, type.Bug

#224 Add support to handle interruption (CTRL+C) from user
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, severity.High, type.Bug

#227 Update developer guide table of contents anchors
  docs/DeveloperGuide.md
  docs/_config.yml
Labels: priority.High, type.Documentation

#226 Update log generation in different platform
  src/main/java/seedu/duke/logger/ScrumLogger.java
  src/main/java/seedu/duke/parser/ParserManager.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.Low, type.Bug

#222 Doc v2.1
  README.md
  docs/DeveloperGuide.md
  docs/image/developerguide/storage_load.png
  docs/image/developerguide/storage_load_parse.png
  docs/image/developerguide/storage_save.png
  docs/image/developerguide/storage_save_serialise.png
Labels: priority.High, type.Documentation

#230 Add PPP for chocomango
  docs/team/chocomango.md
Labels: priority.High, severity.Low, type.Documentation

#231 PPP
  docs/team/e0426051.md
Labels: priority.High, severity.Low, type.Documentation

#235 Update DG anchors
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#236 Update README
  README.md
  docs/AboutUs.md
  docs/image/readme/select_checkstyle.png
  docs/image/readme/select_gradle.png
  docs/image/readme/select_test.png
Labels: priority.High, type.Documentation

#239 Fix some header links
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#242 Fix spelling error
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#245 Added missing explanation to logic
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#246 Update help command summary
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#247 Update Docs
  docs/UserGuide.md
  docs/team/keke101.md
Labels: priority.High, type.Documentation

#248 Update DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/image/developerguide/storage_save.png
  docs/image/developerguide/storage_save_1.png
  docs/image/developerguide/storage_save_2.png
Labels: priority.High, type.Documentation

#251 PPP Final
  docs/team/homingjun.md
Labels: priority.High, type.Documentation

#252 Add profile photo to AboutUs
  docs/AboutUs.md
  docs/image/aboutus/MingJun.png
Labels: priority.High, type.Documentation

#253 Update PPP and AboutUs.md
  docs/AboutUs.md
  docs/image/aboutus/keke101.png
  docs/team/keke101.md
Labels: priority.High

#255 Fix PPP
  docs/team/keke101.md
Labels: priority.High, type.Bug, type.Documentation

#256 Finalise
  docs/team/chocomango.md
  src/main/java/com/scrumptious/command/sprint/AddSprintTaskCommand.java
  src/main/java/com/scrumptious/command/sprint/AllocateSprintTaskCommand.java
  src/main/java/com/scrumptious/command/sprint/CreateSprintCommand.java
  src/main/java/com/scrumptious/command/sprint/DeallocateSprintTaskCommand.java
  src/main/java/com/scrumptious/command/sprint/EditSprintCommand.java
  src/main/java/com/scrumptious/command/sprint/RemoveSprintTaskCommand.java
  src/main/java/com/scrumptious/command/sprint/SprintCommand.java
  src/main/java/com/scrumptious/command/sprint/ViewSprintCommand.java
  src/test/java/com/scrumptious/command/sprint/AddSprintTaskCommandTest.java
  src/test/java/com/scrumptious/command/sprint/AllocateSprintTaskCommandTest.java
  src/test/java/com/scrumptious/command/sprint/CreateSprintCommandTest.java
  src/test/java/com/scrumptious/command/sprint/DeallocateSprintTaskCommandTest.java
  src/test/java/com/scrumptious/command/sprint/EditSprintCommandTest.java
  src/test/java/com/scrumptious/command/sprint/RemoveSprintTaskCommandTest.java
  src/test/java/com/scrumptious/command/sprint/SprintCommandTest.java
  src/test/java/com/scrumptious/command/sprint/ViewSprintCommandTest.java
Labels: priority.Low, severity.Low, type.Documentation, type.Enhancement
